//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RDPplus.Pages.Menu_rdp.pengembalian_kunci_rdp
{


    public partial class pengembalian_kunci_rdp
    {
    }
}
